In [ ]:
weather_data=api.get("Weather_data")
weather_contion=api.get("Weather Poluttion")
df=pd.reda_csv9("car accciend ")

1. I will merge weather_data and weather_contion with df
2. I will write data to database

In [1]:
import seaborn as sns

df = sns.load_dataset("titanic")

In [2]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
from dotenv import load_dotenv
import os
load_dotenv(".env")

True

In [10]:
MYSQL_USER=os.getenv('MYSQL_USER')
MYSQL_PASSWORD=os.getenv('MYSQL_PASSWORD')
MYSQL_DATABASE=os.getenv('MYSQL_DATABASE')

In [ ]:
from sqlalchemy import create_engine
DATABASE_URL = (
    f"mysql+pymysql://{os.getenv('MYSQL_USER')}:{os.getenv('MYSQL_PASSWORD')}"
    f"@172.20.0.2:3306/{os.getenv('MYSQL_DATABASE')}"
)

engine = create_engine(DATABASE_URL, echo=False)

In [12]:
engine

Engine(mysql+pymysql://MYSQL_USER:***@172.20.0.2:3306/MYSQL_DATABASE)

In [13]:
df.to_sql("titantic", con=engine, if_exists="replace", index=False )

2026-06-14 17:49:40,615 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2026-06-14 17:49:40,615 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-14 17:49:40,617 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2026-06-14 17:49:40,618 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-14 17:49:40,619 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2026-06-14 17:49:40,620 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-14 17:49:40,622 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-06-14 17:49:40,625 INFO sqlalchemy.engine.Engine DESCRIBE `MYSQL_DATABASE`.`titantic`
2026-06-14 17:49:40,626 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-14 17:49:40,635 INFO sqlalchemy.engine.Engine
CREATE TABLE titantic (
	survived BIGINT,
	pclass BIGINT,
	sex TEXT,
	age FLOAT(53),
	sibsp BIGINT,
	parch BIGINT,
	fare FLOAT(53),
	embarked TEXT,
	class TEXT,
	who TEXT,
	adult_male BOOL,
	deck TEXT,
	embark_town TEXT,
	alive TEXT,
	alone BOOL
)


2026-06-14 17:49:40,636 INFO sqlalchemy.engine.Engine [no key 0.00098s] {}
2026-06-14 17:49:40,660 INFO sqlalchemy.engine.Engine INSERT INTO titantic (survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone) VALUES (%(survived)s, %(pclass)s, %(sex)s, %(age)s, %(sibsp)s, %(parch)s, %(fare)s, %(embarked)s, %(class)s, %(who)s, %(adult_male)s, %(deck)s, %(embark_town)s, %(alive)s, %(alone)s)
2026-06-14 17:49:40,661 INFO sqlalchemy.engine.Engine [generated in 0.00915s] [{'survived': 0, 'pclass': 3, 'sex': 'male', 'age': 22.0, 'sibsp': 1, 'parch': 0, 'fare': 7.25, 'embarked': 'S', 'class': 'Third', 'who': 'man', 'adult_male': 1, 'deck': None, 'embark_town': 'Southampton', 'alive': 'no', 'alone': 0}, {'survived': 1, 'pclass': 1, 'sex': 'female', 'age': 38.0, 'sibsp': 1, 'parch': 0, 'fare': 71.2833, 'embarked': 'C', 'class': 'First', 'who': 'woman', 'adult_male': 0, 'deck': 'C', 'embark_town': 'Cherbourg', 'alive': 'yes', 'alone': 0}, {'survived': 1, 'pclass': 3, 'sex': 'female', 'age': 26.0, 'sibsp': 0, 'parch': 0, 'fare': 7.925, 'embarked': 'S', 'class': 'Third', 'who': 'woman', 'adult_male': 0, 'deck': None, 'embark_town': 'Southampton', 'alive': 'yes', 'alone': 1}, {'survived': 1, 'pclass': 1, 'sex': 'female', 'age': 35.0, 'sibsp': 1, 'parch': 0, 'fare': 53.1, 'embarked': 'S', 'class': 'First', 'who': 'woman', 'adult_male': 0, 'deck': 'C', 'embark_town': 'Southampton', 'alive': 'yes', 'alone': 0}, {'survived': 0, 'pclass': 3, 'sex': 'male', 'age': 35.0, 'sibsp': 0, 'parch': 0, 'fare': 8.05, 'embarked': 'S', 'class': 'Third', 'who': 'man', 'adult_male': 1, 'deck': None, 'embark_town': 'Southampton', 'alive': 'no', 'alone': 1}, {'survived': 0, 'pclass': 3, 'sex': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'fare': 8.4583, 'embarked': 'Q', 'class': 'Third', 'who': 'man', 'adult_male': 1, 'deck': None, 'embark_town': 'Queenstown', 'alive': 'no', 'alone': 1}, {'survived': 0, 'pclass': 1, 'sex': 'male', 'age': 54.0, 'sibsp': 0, 'parch': 0, 'fare': 51.8625, 'embarked': 'S', 'class': 'First', 'who': 'man', 'adult_male': 1, 'deck': 'E', 'embark_town': 'Southampton', 'alive': 'no', 'alone': 1}, {'survived': 0, 'pclass': 3, 'sex': 'male', 'age': 2.0, 'sibsp': 3, 'parch': 1, 'fare': 21.075, 'embarked': 'S', 'class': 'Third', 'who': 'child', 'adult_male': 0, 'deck': None, 'embark_town': 'Southampton', 'alive': 'no', 'alone': 0}  ... displaying 10 of 891 total bound parameter sets ...  {'survived': 1, 'pclass': 1, 'sex': 'male', 'age': 26.0, 'sibsp': 0, 'parch': 0, 'fare': 30.0, 'embarked': 'C', 'class': 'First', 'who': 'man', 'adult_male': 1, 'deck': 'C', 'embark_town': 'Cherbourg', 'alive': 'yes', 'alone': 1}, {'survived': 0, 'pclass': 3, 'sex': 'male', 'age': 32.0, 'sibsp': 0, 'parch': 0, 'fare': 7.75, 'embarked': 'Q', 'class': 'Third', 'who': 'man', 'adult_male': 1, 'deck': None, 'embark_town': 'Queenstown', 'alive': 'no', 'alone': 1}]
2026-06-14 17:49:40,880 INFO sqlalchemy.engine.Engine COMMIT

891

In [15]:
import pandas as pd

In [16]:
my_df=pd.read_sql("Select *  from titantic", con=engine)

2026-06-14 17:54:12,224 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-06-14 17:54:12,226 INFO sqlalchemy.engine.Engine DESCRIBE `MYSQL_DATABASE`.`Select *  from titantic`
2026-06-14 17:54:12,230 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-14 17:54:12,236 INFO sqlalchemy.engine.Engine Select *  from titantic
2026-06-14 17:54:12,239 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-14 17:54:12,270 INFO sqlalchemy.engine.Engine ROLLBACK

In [18]:
my_df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,1,NaN,Southampton,no,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,0,C,Cherbourg,yes,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,0,NaN,Southampton,yes,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,NaN,Southampton,no,1